version: '3.8'

services:
  catalog-service:
    build:
      context: ./catalog-service
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb
      - elasticsearch
    environment:
      SPRING_PROFILES_ACTIVE: docker

  booking-service:
    build:
      context: ./booking-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"