spring:
    application:
        name: api-gateway
    cloud:
        gateway:
          routes:
              - id: booking-service
                uri: lb://BOOKING-SERVICE
                predicates:
                    - Path=/booking/**
                filters:
                    - RewritePath=/booking/(?<segment>.*), /$\{segment}
              - id: notification-service
                uri: lb://NOTIFICATION-SERVICE
                predicates:
                    - Path=/notification/**
                filters:
                    - RewritePath=/notification/(?<segment>.*), /$\{segment}
              - id: catalog-service
                uri: lb://CATALOG-SERVICE
                predicates:
                    - Path=/catalog/**
                filters:
                    - RewritePath=/catalog/(?<segment>.*), /$\{segment}
